// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service.go

// Package internal is a generated GoMock package.
package internal

import (
	model "main/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockActions is a mock of Actions interface.
type MockActions struct {
	ctrl     *gomock.Controller
	recorder *MockActionsMockRecorder
}

// MockActionsMockRecorder is the mock recorder for MockActions.
type MockActionsMockRecorder struct {
	mock *MockActions
}

// NewMockActions creates a new mock instance.
func NewMockActions(ctrl *gomock.Controller) *MockActions {
	mock := &MockActions{ctrl: ctrl}
	mock.recorder = &MockActionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActions) EXPECT() *MockActionsMockRecorder {
	return m.recorder
}

// PostBinaryTreeSum mocks base method.
func (m *MockActions) PostBinaryTreeSum(tree *model.Tree) (*model.BinaryTreeSum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostBinaryTreeSum", tree)
	ret0, _ := ret[0].(*model.BinaryTreeSum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostBinaryTreeSum indicates an expected call of PostBinaryTreeSum.
func (mr *MockActionsMockRecorder) PostBinaryTreeSum(tree interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostBinaryTreeSum", reflect.TypeOf((*MockActions)(nil).PostBinaryTreeSum), tree)
}
